import { ref } from 'vue'

const currentLanguage = ref(localStorage.getItem('erp_pref_lang') || 'ID')

const translations = {
  ID: {
    // Top Bar & General
    all_branches: 'Semua Outlet', 
    cashier_status: 'STATUS KASIR', 
    active_shift: 'Shift aktif saat ini', 
    starting_cash: 'Kas Awal: Rp', 
    shift_closed_msg: 'Kasir tertutup. Masuk dari laman POS.', 
    enter_pos: 'Masuk ke POS', 
    account: 'AKUN', 
    edit_profile: 'Edit Profil', 
    change_pass: 'Ganti Password', 
    preferences: 'PREFERENSI', 
    language: 'Bahasa', 
    logout: 'Keluar Aplikasi', 
    prof_success: 'Profil berhasil diperbaharui.', 
    prof_fail: 'Gagal memperbaharui profil: ', 
    pass_req: 'Password harus diisi.', 
    pass_min: 'Password minimal 6 karakter.', 
    pass_match: 'Konfirmasi password tidak cocok.', 
    pass_success: 'Password berhasil diganti! Mohon ingat password baru Anda.', 
    pass_fail: 'Gagal mengganti password: ',
    new_pass: 'Password Baru', 
    conf_pass: 'Konfirmasi Password Baru', 
    cancel: 'Batal', 
    save_prof: 'Simpan Profil', 
    save_pass: 'Simpan Password', 
    choose_lang: 'Pilih Bahasa',
    full_name: 'Nama Lengkap', 
    email_addr: 'Alamat Email',
    ph_name: 'Masukkan nama...', 
    ph_email: 'email@contoh.com', 
    ph_new_pass: 'Minimal 6 karakter', 
    ph_conf_pass: 'Ketik ulang password baru',
    close: 'Tutup',
    save: 'Simpan',
    
    // Sidebar Navigation
    nav_pos: 'Kasir POS',
    nav_tables: 'Denah Meja',
    nav_menu: 'Daftar Menu',
    nav_kitchen: 'Kitchen Display',
    nav_history: 'Riwayat Transaksi Resto',
    nav_reports: 'Laporan Harian Resto',
    nav_settings: 'Pengaturan Sistem Resto',

    // POS & Core
    subtotal: 'Subtotal',
    discount: 'Diskon',
    tax: 'Pajak',
    service: 'Service',
    total_payment: 'Total Bayar',
    pay: 'Bayar',
    print_receipt: 'Cetak Struk',
    cart_empty: 'Keranjang Kosong',
    category_all: 'Semua',
    search_menu: 'Cari menu...',
    out_of_stock: 'HABIS',
    item_unavailable: 'Menu tidak tersedia.',

    // Tables
    table_map: 'Denah Meja',
    edit_mode: 'Mode Edit Aktif',
    organize_tables: 'Atur Denah / Edit Mode',
    save_map: 'Simpan Denah',
    add_table: 'Tambah Meja',
    empty_tables: 'Tidak ada meja ditambahkan. Klik "Tambah Meja".',

    // Kitchen
    kitchen_display: 'Kitchen Display',
    orders_processing: 'Pesanan Sedang Diproses',
    turn_on_audio: 'Nyalakan Audio Masuk',
    audio_on: 'Audio Aktif',
    refresh_now: 'Segarkan Sekarang',
    start_cooking: 'MULAI MASAK',
    all_ready: 'SEMUA SIAP',
    is_cooking: 'SEDANG DIMASAK',
    call_serve: 'PANGGIL & SAJIKAN',
    empty_kitchen: 'Dapur Kosong! 🎉',
    empty_kitchen_msg: 'Luar biasa! Tidak ada antrian pesanan saat ini.',

    // Modals
    add_room: 'Tambah Ruangan',
    edit_room: 'Edit Ruangan',
    room_name: 'Nama Ruangan',
    placeholder_room_name: 'Contoh: Lt. 1 Indoor',
    description: 'Deskripsi',
    add_table: 'Tambah Meja',
    edit_table: 'Edit Meja',
    table_number: 'Nomor Meja',
    placeholder_table_number: 'Contoh: 12 atau A1',
    capacity: 'Kapasitas',
    label: 'Label',
    optional: 'opsional',
    placeholder_table_label: 'Contoh: Dekat Jendela',
    select_room: 'Pilih Ruangan',
    no_room: 'Tanpa Ruangan',
    status: 'Status',
    available: 'Tersedia',
    occupied: 'Terisi',
    reserved: 'Dipesan',
    cleaning: 'Pembersihan',
    table_shape: 'Bentuk Meja',
    square: 'Kotak',
    round: 'Bulat',
    rectangle: 'Persegi Pj.',
    edit_table_data: 'Edit Data Meja',
    change_status: 'Ubah Status'
  },
  EN: {
    all_branches: 'All Branches', 
    cashier_status: 'CASHIER STATUS', 
    active_shift: 'Current active shift', 
    starting_cash: 'Starting Cash: Rp', 
    shift_closed_msg: 'Cashier closed. Enter from POS page.', 
    enter_pos: 'Enter POS', 
    account: 'ACCOUNT', 
    edit_profile: 'Edit Profile', 
    change_pass: 'Change Password', 
    preferences: 'PREFERENCES', 
    language: 'Language', 
    logout: 'Log Out', 
    prof_success: 'Profile updated successfully.', 
    prof_fail: 'Failed to update profile: ', 
    pass_req: 'Password is required.', 
    pass_min: 'Password must be at least 6 characters.', 
    pass_match: 'Password confirmation does not match.', 
    pass_success: 'Password changed successfully! Please remember your new password.', 
    pass_fail: 'Failed to change password: ',
    new_pass: 'New Password', 
    conf_pass: 'Confirm New Password', 
    cancel: 'Cancel', 
    save_prof: 'Save Profile', 
    save_pass: 'Save Password', 
    choose_lang: 'Select Language',
    full_name: 'Full Name', 
    email_addr: 'Email Address',
    ph_name: 'Enter name...', 
    ph_email: 'email@example.com', 
    ph_new_pass: 'Min. 6 characters', 
    ph_conf_pass: 'Retype new password',
    close: 'Close',
    save: 'Save',
    
    nav_pos: 'POS Cashier',
    nav_tables: 'Table Layout',
    nav_menu: 'Menu Catalog',
    nav_kitchen: 'Kitchen Display',
    nav_history: 'Transaction History',
    nav_reports: 'Daily Reports',
    nav_settings: 'System Settings',

    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    service: 'Service',
    total_payment: 'Total Payment',
    pay: 'Pay',
    print_receipt: 'Print Receipt',
    cart_empty: 'Cart Empty',
    category_all: 'All',
    search_menu: 'Search menu...',
    out_of_stock: 'OUT OF STOCK',
    item_unavailable: 'Item unavailable.',

    table_map: 'Table Layout',
    edit_mode: 'Edit Mode Active',
    organize_tables: 'Organize Layout / Edit Mode',
    save_map: 'Save Layout',
    add_table: 'Add Table',
    empty_tables: 'No tables added yet. Click "Add Table".',

    kitchen_display: 'Kitchen Display',
    orders_processing: 'Orders Processing',
    turn_on_audio: 'Turn On Audio Notif',
    audio_on: 'Audio Active',
    refresh_now: 'Refresh Now',
    start_cooking: 'START COOKING',
    all_ready: 'ALL READY',
    is_cooking: 'COOKING',
    call_serve: 'CALL & SERVE',
    empty_kitchen: 'Kitchen Empty! 🎉',
    empty_kitchen_msg: 'Great job! No pending orders right now.',

    // Modals
    add_room: 'Add Room',
    edit_room: 'Edit Room',
    room_name: 'Room Name',
    placeholder_room_name: 'E.g. 1st Floor Indoor',
    description: 'Description',
    add_table: 'Add Table',
    edit_table: 'Edit Table',
    table_number: 'Table Number',
    placeholder_table_number: 'E.g. 12 or A1',
    capacity: 'Capacity',
    label: 'Label',
    optional: 'optional',
    placeholder_table_label: 'E.g. Near Window',
    select_room: 'Select Room',
    no_room: 'No Room',
    status: 'Status',
    available: 'Available',
    occupied: 'Occupied',
    reserved: 'Reserved',
    cleaning: 'Cleaning',
    table_shape: 'Table Shape',
    square: 'Square',
    round: 'Round',
    rectangle: 'Rectangle',
    edit_table_data: 'Edit Table Data',
    change_status: 'Change Status'
  }
}

export function useLang() {
  function t(key) {
    return translations[currentLanguage.value]?.[key] || key
  }

  function setLanguage(lang) {
    currentLanguage.value = lang
    localStorage.setItem('erp_pref_lang', lang)
  }

  return {
    currentLanguage,
    t,
    setLanguage
  }
}
